# Generated by Django 5.0.6 on 2025-10-23 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.CharField(editable=False, max_length=16, primary_key=True, serialize=False)),
                ('target', models.URLField()),
                ('password_hash', models.CharField(blank=True, max_length=128, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('analytics_opt_in', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
