# Generated by Django 5.0.6 on 2025-10-23 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='require_password',
            field=models.BooleanField(default=False),
        ),
    ]
