# Generated by Django 5.0.6 on 2025-10-24 17:25

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_link_require_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClickEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ts', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('event', models.CharField(choices=[('preview', 'preview'), ('redirect', 'redirect')], max_length=16)),
                ('verdict_label', models.CharField(default='safe', max_length=12)),
                ('verdict_score', models.FloatField(default=0.0)),
                ('referrer', models.CharField(blank=True, default='', max_length=256)),
                ('ua_hash', models.CharField(blank=True, default='', max_length=64)),
                ('country', models.CharField(blank=True, default='', max_length=2)),
                ('success', models.BooleanField(default=True)),
                ('link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='app.link')),
            ],
            options={
                'indexes': [models.Index(fields=['link', 'ts'], name='app_clickev_link_id_197af0_idx'), models.Index(fields=['verdict_label'], name='app_clickev_verdict_3ee19f_idx')],
            },
        ),
    ]
