# Generated by Django 5.0.6 on 2025-11-19 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_emailotp'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='emailotp',
            new_name='app_emailot_user_id_454128_idx',
            old_name='app_emailo_user_id_e4dca0_idx',
        ),
        migrations.RenameIndex(
            model_name='emailotp',
            new_name='app_emailot_expires_0c31cf_idx',
            old_name='app_emailo_expires_b4237c_idx',
        ),
        migrations.AlterField(
            model_name='clickevent',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
